name: "face_recognition_postprocess"
backend: "dali"
max_batch_size: 32

input [
  {
    name: "embeddings"
    data_type: TYPE_FP32
    # Chỉ khai báo chiều dữ liệu đơn lẻ (không chứa chiều batch)
    dims: [ 512 ]
  }
]

output [
  {
    name: "norm_embeddings"
    data_type: TYPE_FP32
    # Chỉ khai báo chiều dữ liệu đơn lẻ (không chứa chiều batch)
    dims: [ 512 ]
  }
]

instance_group [
  {
    name: "gpu_0"
    kind: KIND_GPU
    gpus: [ 0 ]
    count: 1
  }
]
